// Generated by gencpp from file ex2/first_srv.msg
// DO NOT EDIT!


#ifndef EX2_MESSAGE_FIRST_SRV_H
#define EX2_MESSAGE_FIRST_SRV_H

#include <ros/service_traits.h>


#include <ex2/first_srvRequest.h>
#include <ex2/first_srvResponse.h>


namespace ex2
{

struct first_srv
{

typedef first_srvRequest Request;
typedef first_srvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct first_srv
} // namespace ex2


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ex2::first_srv > {
  static const char* value()
  {
    return "13364833f0478803e63d07b0985a346c";
  }

  static const char* value(const ::ex2::first_srv&) { return value(); }
};

template<>
struct DataType< ::ex2::first_srv > {
  static const char* value()
  {
    return "ex2/first_srv";
  }

  static const char* value(const ::ex2::first_srv&) { return value(); }
};


// service_traits::MD5Sum< ::ex2::first_srvRequest> should match
// service_traits::MD5Sum< ::ex2::first_srv >
template<>
struct MD5Sum< ::ex2::first_srvRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ex2::first_srv >::value();
  }
  static const char* value(const ::ex2::first_srvRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ex2::first_srvRequest> should match
// service_traits::DataType< ::ex2::first_srv >
template<>
struct DataType< ::ex2::first_srvRequest>
{
  static const char* value()
  {
    return DataType< ::ex2::first_srv >::value();
  }
  static const char* value(const ::ex2::first_srvRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ex2::first_srvResponse> should match
// service_traits::MD5Sum< ::ex2::first_srv >
template<>
struct MD5Sum< ::ex2::first_srvResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ex2::first_srv >::value();
  }
  static const char* value(const ::ex2::first_srvResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ex2::first_srvResponse> should match
// service_traits::DataType< ::ex2::first_srv >
template<>
struct DataType< ::ex2::first_srvResponse>
{
  static const char* value()
  {
    return DataType< ::ex2::first_srv >::value();
  }
  static const char* value(const ::ex2::first_srvResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // EX2_MESSAGE_FIRST_SRV_H
