// Generated by gencpp from file ex2/first_srvRequest.msg
// DO NOT EDIT!


#ifndef EX2_MESSAGE_FIRST_SRVREQUEST_H
#define EX2_MESSAGE_FIRST_SRVREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ex2
{
template <class ContainerAllocator>
struct first_srvRequest_
{
  typedef first_srvRequest_<ContainerAllocator> Type;

  first_srvRequest_()
    : str1()
    , str2()  {
    }
  first_srvRequest_(const ContainerAllocator& _alloc)
    : str1(_alloc)
    , str2(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _str1_type;
  _str1_type str1;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _str2_type;
  _str2_type str2;





  typedef boost::shared_ptr< ::ex2::first_srvRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ex2::first_srvRequest_<ContainerAllocator> const> ConstPtr;

}; // struct first_srvRequest_

typedef ::ex2::first_srvRequest_<std::allocator<void> > first_srvRequest;

typedef boost::shared_ptr< ::ex2::first_srvRequest > first_srvRequestPtr;
typedef boost::shared_ptr< ::ex2::first_srvRequest const> first_srvRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ex2::first_srvRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ex2::first_srvRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ex2::first_srvRequest_<ContainerAllocator1> & lhs, const ::ex2::first_srvRequest_<ContainerAllocator2> & rhs)
{
  return lhs.str1 == rhs.str1 &&
    lhs.str2 == rhs.str2;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ex2::first_srvRequest_<ContainerAllocator1> & lhs, const ::ex2::first_srvRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ex2

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::ex2::first_srvRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ex2::first_srvRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ex2::first_srvRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ex2::first_srvRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ex2::first_srvRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ex2::first_srvRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ex2::first_srvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "34df8d240c5fbb34c73f630b5f4c576b";
  }

  static const char* value(const ::ex2::first_srvRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x34df8d240c5fbb34ULL;
  static const uint64_t static_value2 = 0xc73f630b5f4c576bULL;
};

template<class ContainerAllocator>
struct DataType< ::ex2::first_srvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ex2/first_srvRequest";
  }

  static const char* value(const ::ex2::first_srvRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ex2::first_srvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string str1\n"
"string str2\n"
;
  }

  static const char* value(const ::ex2::first_srvRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ex2::first_srvRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.str1);
      stream.next(m.str2);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct first_srvRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ex2::first_srvRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ex2::first_srvRequest_<ContainerAllocator>& v)
  {
    s << indent << "str1: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.str1);
    s << indent << "str2: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.str2);
  }
};

} // namespace message_operations
} // namespace ros

#endif // EX2_MESSAGE_FIRST_SRVREQUEST_H
