// Generated by gencpp from file ex2/first_srvResponse.msg
// DO NOT EDIT!


#ifndef EX2_MESSAGE_FIRST_SRVRESPONSE_H
#define EX2_MESSAGE_FIRST_SRVRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ex2
{
template <class ContainerAllocator>
struct first_srvResponse_
{
  typedef first_srvResponse_<ContainerAllocator> Type;

  first_srvResponse_()
    : ans()  {
    }
  first_srvResponse_(const ContainerAllocator& _alloc)
    : ans(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _ans_type;
  _ans_type ans;





  typedef boost::shared_ptr< ::ex2::first_srvResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ex2::first_srvResponse_<ContainerAllocator> const> ConstPtr;

}; // struct first_srvResponse_

typedef ::ex2::first_srvResponse_<std::allocator<void> > first_srvResponse;

typedef boost::shared_ptr< ::ex2::first_srvResponse > first_srvResponsePtr;
typedef boost::shared_ptr< ::ex2::first_srvResponse const> first_srvResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ex2::first_srvResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ex2::first_srvResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ex2::first_srvResponse_<ContainerAllocator1> & lhs, const ::ex2::first_srvResponse_<ContainerAllocator2> & rhs)
{
  return lhs.ans == rhs.ans;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ex2::first_srvResponse_<ContainerAllocator1> & lhs, const ::ex2::first_srvResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ex2

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::ex2::first_srvResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ex2::first_srvResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ex2::first_srvResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ex2::first_srvResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ex2::first_srvResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ex2::first_srvResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ex2::first_srvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "65c770945c83e7be8dd04ade02be6046";
  }

  static const char* value(const ::ex2::first_srvResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x65c770945c83e7beULL;
  static const uint64_t static_value2 = 0x8dd04ade02be6046ULL;
};

template<class ContainerAllocator>
struct DataType< ::ex2::first_srvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ex2/first_srvResponse";
  }

  static const char* value(const ::ex2::first_srvResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ex2::first_srvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string ans\n"
"\n"
;
  }

  static const char* value(const ::ex2::first_srvResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ex2::first_srvResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.ans);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct first_srvResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ex2::first_srvResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ex2::first_srvResponse_<ContainerAllocator>& v)
  {
    s << indent << "ans: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.ans);
  }
};

} // namespace message_operations
} // namespace ros

#endif // EX2_MESSAGE_FIRST_SRVRESPONSE_H
